---
- name: Collect Juniper Diagnositics
  hosts: junos-devices
  connection: local
  gather_facts: no
  roles:
  - Juniper.junos

  vars_prompt:
  - name: USER
    prompt: Junos Device(s) Username
    private: no

  - name: PWD
    prompt: Junos Device(s) Password
    private: yes

  - name: FTP_HOST
    prompt: Destination FTP Host IP
    private: no

  - name: FTP_USER
    prompt: FTP Username
    private: no

  - name: FTP_PWD
    prompt: FTP Password
    private: yes

  tasks:
  - name: Generate a directory for the pending output
    set_fact:
      out_dir: ~/playbooks/outputs
#      ftp_host: 192.168.112.151

  - name: Confirm/Create the output directory
    file:
      path: "{{ out_dir }}"
      state: directory

  - name: Issuing a Request Support Information (RSI) from device
    juniper_junos_rpc:
      rpcs:
        - "get-support-information"
      output: text
      dest_dir: "{{ out_dir }}"
      provider:
        host: "{{ ansible_host }}"
        user: "{{ USER }}"
        passwd: "{{ PWD }}"
        port: 830
        timeout: 600
    register: rsi

  - name: Collecting all logs from device
    juniper_junos_command:
      command:
        - "file archive compress source /var/log/* destination ftp://{{ FTP_USER }}:{{ FTP_PWD }}@{{ FTP_HOST }}/{{ inventory_hostname }}.logs.tgz"
      provider:
        host: "{{ ansible_host }}"
        user: "{{ USER }}"
        passwd: "{{ PWD }}"
        port: 22
        timeout: 600
    register: logs

  - name: Collecting all coredumps from devices
    juniper_junos_command:
      commands:
        - "file archive compress source /var/tmp/*core* destination ftp://{{ FTP_USER }}:{{ FTP_PWD }}@{{ FTP_HOST }}/{{ inventory_hostname }}.tmpcores.tgz"
        - "file archive compress source /var/crash/*core* destination ftp://{{ FTP_USER }}:{{ FTP_PWD }}@{{ FTP_HOST }}/{{ inventory_hostname }}.crashcores.tgz"
      provider:
        host: "{{ ansible_host }}"
        user: "{{ USER }}"
        passwd: "{{ PWD }}"
        port: 22
        timeout: 600
    register: logs
