---
- name: Get Device Port Status
  hosts: junos-devices
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
  - name: USER
    prompt: Junos Device(s) Username
    private: no

  - name: PWD
    prompt: Junos Device(s) Password
    private: yes

  tasks:
  - name: Generate a directory for the pending output
    set_fact:
      out_dir: ~/playbooks/outputs

  - name: Confirm/Create the output directory
    file:
      path: "{{ out_dir }}"
      state: directory

  - name: Get Interface Information
    juniper_junos_command:
      commands:
        - 'show interface terse media'
      format: text
#      format: xml
#      format: json
      dest_dir: "{{ out_dir }}"
      provider:
        host: "{{ ansible_host }}"
        user: "{{ USER }}"
        passwd: "{{ PWD }}"
#        port: 830
#        timeout: 600
    register: junos_interfaces

  - name: Print results
    debug:
      var: junos_interfaces.stdout_lines 
